version: "3.8"

services:
  api:
    image: hcommenter:current
    build:
      context: hCommenter.Api
      dockerfile: build.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .env.local
