/* tslint:disable */
/* eslint-disable */
/**
 * hCommenter.API
 * An API for creating and retrieving conversation comments.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NewComment
 */
export interface NewComment {
    /**
     * 
     * @type {string}
     * @memberof NewComment
     */
    'message': string;
    /**
     * 
     * @type {number}
     * @memberof NewComment
     */
    'parent'?: number;
    /**
     * 
     * @type {string}
     * @memberof NewComment
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof NewComment
     */
    'convoUrl': string;
}

