/* tslint:disable */
/* eslint-disable */
/**
 * hCommenter.API
 * An API for creating and retrieving conversation comments.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaginationData
 */
export interface PaginationData {
    /**
     * 
     * @type {number}
     * @memberof PaginationData
     */
    'totalReplies': number;
    /**
     * 
     * @type {number}
     * @memberof PaginationData
     */
    'cursor': number;
}

