/* tslint:disable */
/* eslint-disable */
/**
 * hCommenter.API
 * An API for creating and retrieving conversation comments.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaginationData } from './pagination-data';
// May contain unused imports in some cases
// @ts-ignore
import type { ViewComment } from './view-comment';

/**
 * 
 * @export
 * @interface Paginated
 */
export interface Paginated {
    /**
     * 
     * @type {Array<ViewComment>}
     * @memberof Paginated
     */
    'info': Array<ViewComment>;
    /**
     * 
     * @type {PaginationData}
     * @memberof Paginated
     */
    'pagination': PaginationData;
}

