/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * hCommenter.API
 * An API for creating and retrieving conversation comments.
 * OpenAPI spec version: 1.0
 */

export type GetCommentsUserUsernameSortby =
  (typeof GetCommentsUserUsernameSortby)[keyof typeof GetCommentsUserUsernameSortby];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCommentsUserUsernameSortby = {
  Old: "Old",
  New: "New",
  Popular: "Popular",
  Controversial: "Controversial",
} as const;
