/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * hCommenter.API
 * An API for creating and retrieving conversation comments.
 * OpenAPI spec version: 1.0
 */
import type { GetCommentsConversationConvoUrlSortby } from "./getCommentsConversationConvoUrlSortby";

export type GetCommentsConversationConvoUrlParams = {
  sortby?: GetCommentsConversationConvoUrlSortby;
};
