/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * hCommenter.API
 * An API for creating and retrieving conversation comments.
 * OpenAPI spec version: 1.0
 */
import type { ViewComment } from "./viewComment";
import type { PaginationData } from "./paginationData";

export interface Paginated {
  info: ViewComment[];
  pagination: PaginationData;
}
