/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * hCommenter.API
 * An API for creating and retrieving conversation comments.
 * OpenAPI spec version: 1.0
 */

export type PostCommentsDeleteIdSortby =
  (typeof PostCommentsDeleteIdSortby)[keyof typeof PostCommentsDeleteIdSortby];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCommentsDeleteIdSortby = {
  Old: "Old",
  New: "New",
  Popular: "Popular",
  Controversial: "Controversial",
} as const;
