/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * hCommenter.API
 * An API for creating and retrieving conversation comments.
 * OpenAPI spec version: 1.0
 */

export type UTCTime = string;
