/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * hCommenter.API
 * An API for creating and retrieving conversation comments.
 * OpenAPI spec version: 1.0
 */
import type { UTCTime } from "./uTCTime";
import type { Paginated } from "./paginated";

export interface ViewComment {
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  id: number;
  created: UTCTime;
  message: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  score: number;
  replies?: Paginated;
  authorName: string;
  conversationUrl: string;
}
