---
spec-version: 0.38.0
name: hCommenter-Api
version: 0.1.0
synopsis: Backend & experimental frontend for a generic commenting system.
description: N/A
author: Charles Taylor <mail@charlesekkel.me>
maintainer: Charles Taylor <mail@charlesekkel.me>
github: cekkel/hCommenter
category: Web
license: MIT
extra-doc-files:
  - README.md

ghc-options:
  -Wall
  -fno-warn-orphans
  -Wredundant-constraints
  -Werror
  # -fno-warn-unused-imports

language: GHC2024

default-extensions:
  - OverloadedStrings
  - TypeFamilies
  - NoMonomorphismRestriction
  - AllowAmbiguousTypes
  - DuplicateRecordFields
  - OverloadedLabels
  - RecordWildCards
  - MultiWayIf

dependencies:
  - name: base
    version: "^>= 4.20"
    mixin:
      - hiding (Prelude)
  - name: classy-prelude
    mixin:
      - (ClassyPrelude as Prelude)
  - extra
  - time
  - servant
  - servant-server
  - servant-swagger
  - servant-client
  - http-client
  - http-client-tls
  - swagger2
  - wai
  - http-types
  - optics
  - bytestring
  - aeson
  - aeson-pretty
  - containers
  - transformers
  - effectful
  - effectful-core
  - effectful-th
  - effectful-plugin
  - monad-logger
  - katip
  - aeson
  - persistent
  - persistent-sqlite
  - esqueleto
  - resource-pool
  - http-api-data
  - hedgehog
  - warp
  - PyF
  - unordered-containers
  - text
  - uuid

internal-libraries:
  backend:
    visibility: public
    source-dirs: src/backend
    exposed-modules:
      - Server
      - Utils.Generators
    ghc-options: -fplugin=Effectful.Plugin

  frontend:
    visibility: public
    source-dirs: src/frontend
    exposed-modules:
      - FrontendServer
    ghc-options: -fplugin=Effectful.Plugin
    dependencies:
      - hCommenter-Api:backend

executables:
  backend-exe:
    main: Main.hs
    source-dirs: app/backend
    dependencies:
      - hCommenter-Api:backend

  frontend-exe:
    main: Main.hs
    source-dirs: app/frontend
    dependencies:
      - hCommenter-Api:frontend

tests:
  spec:
    cpp-options: -DTEST
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - hspec-hedgehog
      - hedgehog-servant
      - temporary
      - mockery
      - interpolate
      - hspec-wai
      - hCommenter-Api:backend
      - wai-extra
      - http-types
    build-tools: hspec-discover
