name: Build and Deploy

env:
  RESOURCE_GROUP: "hcommenter"
  LOCATION: "australiaeast"
  API_NAME: "hcommenter-api"
  FRONTEND_NAME: "hcommenter-ui"
  GITHUB_USERNAME: "CharlesEkkel"
  CONTAINER_REGISTRY: hcommenter.azurecr.io
  IDENTITY: hcommenter-identity
  TARGET_PORT: 8080

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

permissions:
  id-token: write
  contents: read

jobs:
  runs-on: ubuntu-latest

  build:
    environment: dev
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build docker image
        run: docker build . --tag $CONTAINER_REGISTRY/$API_NAME:$GITHUB_REF

      # - name: Run tests
      #   run: cabal test all

      - name: Push docker image to registry
        run: docker push $CONTAINER_REGISTRY/$API_NAME:$GITHUB_REF

  deploy-dev:
    env:
      APP_ENVIRONMENT: dev-hcommenter
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: $CONTAINER_REGISTRY/$API_NAME:$GITHUB_REF
          resourceGroup: $RESOURCE_GROUP
          containerAppName: $API_NAME
          containerAppEnvironment: ${{ env.APP_ENVIRONMENT }}
          targetPort: $TARGET_PORT
          location: $LOCATION

  #  deploy-production:
  #    steps:
