name: API - Build and Deploy

env:
  RESOURCE_GROUP: "hcommenter"
  LOCATION: "australiaeast"
  API_NAME: "hcommenter-api"
  FRONTEND_NAME: "hcommenter-ui"
  GITHUB_USERNAME: "CharlesEkkel"
  CONTAINER_REGISTRY: ghcr.io/cekkel
  IDENTITY: hcommenter-identity
  TARGET_PORT: 8080

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Workflow run reason tags"
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout branch to deploy
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Task automatically picks up GITHUB_TOKEN to allow pushing to registry
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: hCommenter.Api/
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.API_NAME }}:${{ github.ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Run tests
      #   run: cabal test all

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    env:
      APP_ENVIRONMENT: dev-hcommenter
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # Auth is not required to pull from the public github registry
      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.CONTAINER_REGISTRY }}/${{ env.API_NAME }}:${{ github.ref }}
          resourceGroup: $RESOURCE_GROUP
          containerAppName: $API_NAME
          containerAppEnvironment: ${{ env.APP_ENVIRONMENT }}
          targetPort: $TARGET_PORT
          location: $LOCATION

  #  deploy-production:
  #    steps:
